name: Build app

on:
  push:
    branches: [main, master]
  release:
    types: [published]
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  build:
    name: Build ${{ matrix.arch }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        arch: [aarch64, amd64]
    steps:
      - uses: actions/checkout@v4

      - name: Log in to the container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and publish
        uses: home-assistant/builder@master
        with:
          args: |
            --${{ matrix.arch }} \
            --target media_sync \
            --image media-sync-{arch} \
            --docker-hub ghcr.io/${{ github.repository_owner }} \
            --addon
